name: Ownables SDK Demo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  ownables:
    uses: ./.github/workflows/build-ownables.yml

  wallet:
    concurrency: ci-${{ github.ref }}
    needs: ownables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Enable Corepack
        run: corepack enable
      - name: Yarn Install
        run: yarn install --immutable
      - name: Download Ownables packages
        uses: actions/download-artifact@v5
        with:
          path: ownables-artifacts
          pattern: ownable-*
          merge-multiple: true
      - name: Copy Ownables packages
        run: |
          mkdir public/ownables
          cp ownables-artifacts/*.zip public/ownables
      - name: Build
        env:
          VITE_OWNABLE_EXAMPLES_URL: /ownables
          VITE_WALLETCONNECT_PROJECT_ID: ${{ vars.WALLETCONNECT_PROJECT_ID }}
          VITE_BASE_SEPOLIA_RPC_URL: https://sepolia.base.org
          VITE_BASE_MAINNET_RPC_URL: https://mainnet.base.org
          VITE_BASE_SEPOLIA_EXPLORER_URL: https://sepolia.basescan.org
          VITE_BASE_MAINNET_EXPLORER_URL: https://basescan.org
        run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          folder: dist
